In [1]:
import torch
from scipy.sparse import csr_matrix, vstack

In [2]:
a = torch.rand([8,4, 64]) # 8 batch size, 4 doc length, 64 voc size

In [3]:
values, indices = torch.max(a, dim = 1, keepdim=True)

In [4]:
a

tensor([[[4.3256e-01, 4.1120e-01, 7.3411e-01,  ..., 3.2532e-01,
          4.7160e-01, 8.5539e-01],
         [9.4293e-01, 7.3076e-01, 7.6004e-01,  ..., 6.8945e-01,
          9.5728e-01, 6.4862e-01],
         [8.9709e-01, 1.4690e-01, 5.5702e-01,  ..., 7.4110e-01,
          5.9739e-02, 5.2283e-03],
         [2.9843e-01, 5.2270e-01, 4.4281e-01,  ..., 8.4998e-01,
          7.7924e-01, 2.2082e-01]],

        [[3.6714e-01, 9.9507e-01, 1.2187e-01,  ..., 7.7613e-02,
          9.0787e-01, 6.3306e-02],
         [6.9210e-01, 8.4273e-01, 5.7964e-01,  ..., 8.2597e-01,
          8.2159e-01, 5.5555e-01],
         [3.2833e-01, 4.1674e-01, 8.3518e-01,  ..., 2.0491e-01,
          9.0301e-01, 8.2214e-01],
         [3.9421e-01, 5.0856e-01, 4.6419e-01,  ..., 2.2918e-01,
          5.3357e-01, 4.9946e-01]],

        [[3.5248e-01, 8.4723e-01, 9.9243e-01,  ..., 2.0415e-01,
          4.1951e-01, 1.6478e-01],
         [5.9342e-01, 5.0655e-02, 1.4945e-01,  ..., 9.9110e-01,
          3.4506e-01, 6.6266e-01],
      

In [5]:
values.shape

torch.Size([8, 1, 64])

In [6]:
placeholder = torch.zeros([8, 4, 64])

In [7]:
placeholder.scatter_(1, indices, values)
None

In [8]:
placeholder

tensor([[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.8554],
         [0.9429, 0.7308, 0.7600,  ..., 0.0000, 0.9573, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.8500, 0.0000, 0.0000]],

        [[0.0000, 0.9951, 0.0000,  ..., 0.0000, 0.9079, 0.0000],
         [0.6921, 0.0000, 0.0000,  ..., 0.8260, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.8352,  ..., 0.0000, 0.0000, 0.8221],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.9924,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.9911, 0.0000, 0.0000],
         [0.6272, 0.9964, 0.0000,  ..., 0.0000, 0.9643, 0.9966],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        ...,

        [[0.6757, 0.0000, 0.0000,  ..., 0.0000, 0.5828, 0.6599],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.5487, 0.0000,  ..., 0.6014, 0.0000, 0.0000],
     

In [20]:
[item.to_sparse_csr() for item in placeholder]

[tensor(crow_indices=tensor([ 0, 15, 29, 46, 64]),
        col_indices=tensor([ 3,  5,  9, 10, 11, 13, 20, 22, 24, 26, 27, 30, 42,
                            45, 63,  0,  1,  2,  6, 18, 23, 25, 38, 39, 40, 43,
                            46, 52, 62,  4,  8, 12, 14, 17, 28, 29, 35, 37, 44,
                            48, 50, 51, 53, 55, 56, 58,  7, 15, 16, 19, 21, 31,
                            32, 33, 34, 36, 41, 47, 49, 54, 57, 59, 60, 61]),
        values=tensor([0.8764, 0.8575, 0.9882, 0.9648, 0.7992, 0.5426, 0.1634,
                       0.8931, 0.7473, 0.9835, 0.7123, 0.5764, 0.8665, 0.9447,
                       0.8554, 0.9429, 0.7308, 0.7600, 0.7471, 0.9647, 0.9474,
                       0.7450, 0.6540, 0.8524, 0.7276, 0.9742, 0.8493, 0.8260,
                       0.9573, 0.9987, 0.8877, 0.7441, 0.7542, 0.6329, 0.9272,
                       0.8985, 0.6817, 0.6455, 0.5277, 0.9358, 0.9507, 0.5005,
                       0.9883, 0.9908, 0.7071, 0.9543, 0.7757, 0.9519, 0.9848

In [ ]:
csr_matrix(placeholder[0].numpy())

TypeError: expected dimension <= 2 array or matrix

In [9]:
sparse_placeholder = csr_matrix(placeholder[0].numpy())

In [10]:
sparse_placeholder.sha

(4, 64)

In [11]:
vstack([sparse_placeholder, sparse_placeholder])

<8x64 sparse matrix of type '<class 'numpy.float32'>'
	with 128 stored elements in Compressed Sparse Row format>

In [13]:
torch.einsum("abc,adc->abd", sparse_placeholder, sparse_placeholder).shape

RuntimeError: reshape is not implemented for sparse tensors

In [43]:
indices.shape

torch.Size([8, 6])

In [54]:
values

tensor([[0.9870, 0.9076, 0.8045, 0.7111, 0.9331, 0.9956],
        [0.4566, 0.5471, 0.6978, 0.8263, 0.5582, 0.9057],
        [0.6588, 0.4227, 0.4806, 0.9573, 0.8615, 0.8149],
        [0.4391, 0.6201, 0.7253, 0.9623, 0.4717, 0.6551],
        [0.4474, 0.8339, 0.8506, 0.7985, 0.9820, 0.9904],
        [0.8233, 0.9183, 0.5700, 0.6797, 0.6216, 0.7837],
        [0.6125, 0.9342, 0.8309, 0.4363, 0.9218, 0.7943],
        [0.8024, 0.9845, 0.4851, 0.8692, 0.7523, 0.8090]])

In [56]:
indices

tensor([[1, 1, 1, 1, 1, 2],
        [1, 2, 1, 2, 0, 2],
        [2, 0, 2, 1, 2, 2],
        [1, 0, 2, 1, 2, 1],
        [1, 0, 2, 2, 2, 1],
        [1, 1, 2, 0, 1, 0],
        [1, 2, 2, 1, 0, 1],
        [2, 0, 0, 0, 0, 2]])

In [70]:
bs = 8
q_pad_len = 4
d_pad_len = 6
out_dim = 64


d_rep_full = torch.rand((bs, d_pad_len, out_dim))
q_rep_full = torch.rand((bs, q_pad_len, out_dim))

In [74]:
torch.einsum("abc,adc->abd", d_rep_full, q_rep_full).shape

torch.Size([8, 6, 4])

In [1]:
import torch, os
from transformers import AutoModelForMaskedLM, AutoTokenizer

/home/lamdo/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model_type = "distilbert-base-uncased"
model = AutoModelForMaskedLM.from_pretrained(model_type)
tokenizer = AutoTokenizer.from_pretrained(model_type)

In [4]:
docs = ["machine learning is fun", "machine learning is in no way fun"]

In [5]:
tokens = tokenizer(docs, return_tensors = "pt", padding = True, truncation=True, max_length=256)

In [6]:
tokens["input_ids"], tokens["attention_mask"]

(tensor([[ 101, 3698, 4083, 2003, 4569,  102,    0,    0,    0],
         [ 101, 3698, 4083, 2003, 1999, 2053, 2126, 4569,  102]]),
 tensor([[1, 1, 1, 1, 1, 1, 0, 0, 0],
         [1, 1, 1, 1, 1, 1, 1, 1, 1]]))

In [16]:
test = torch.nn.functional.one_hot(tokens["input_ids"][0], num_classes = 30522)

In [19]:
tokens["input_ids"][0]

tensor([ 101, 3698, 4083, 2003, 4569,  102,    0,    0,    0])

In [23]:
test[1][3698]

tensor(1)

In [8]:
masked_test = test * tokens["attention_mask"][0].unsqueeze(-1)

In [10]:
masked_test.shape

torch.Size([9, 30522])

In [42]:
masked_test[0][-1]

tensor([0, 0, 0,  ..., 0, 0, 0])

In [40]:
test.shape

torch.Size([2, 9, 30522])

In [25]:
values, indices = torch.max(masked_test, dim = 0)

In [28]:
values[tokens["input_ids"][0]]

tensor([1, 1, 1, 1, 1, 1, 0, 0, 0])

In [29]:
indices

tensor([0, 0, 0,  ..., 0, 0, 0])

In [34]:
col = torch.nonzero(values).squeeze().cpu().tolist()
_indices = indices[col].cpu().tolist()

In [35]:
_indices

[0, 5, 3, 1, 2, 4]

In [33]:
col

[[0, 101], [1, 3698], [2, 4083], [3, 2003], [4, 4569], [5, 102]]

In [1]:
with open("/scratch/lamdo/splade_kp_datasets/kp20kbiomed/raw.tsv") as f:
    for line in f:
        query, pos, neg = line.split("\t")
        break

In [2]:
query

'telepresence, animation, avatars, application sharing, collaborative virtual environments'

In [3]:
pos

'virtually enhancing the perception of user actions. This paper proposes using virtual reality to enhance the perception of actions by distant users on a shared application. Here, distance may refer either to space ( e.g. in a remote synchronous collaboration) or time ( e.g. during playback of recorded actions). Our approach consists in immersing the application in a virtual inhabited 3D space and mimicking user actions by animating avatars. We illustrate this approach with two applications, the one for remote collaboration on a shared application and the other to playback recorded sequences of user actions. We suggest this could be a low cost enhancement for telepresence'

In [4]:
neg

'a new method for similarity indexing of market basket data. In recent years, many data mining methods have been proposed for finding useful and structured information from market basket data. The association rule model was recently proposed in order to discover useful patterns and dependencies in such data. This paper discusses a method for indexing market basket data efficiently for similarity search. The technique is likely to be very useful in applications which utilize the similarity in customer buying behavior in order to make peer recommendations. We propose an index called the signature table , which is very flexible in supporting a wide range of similarity functions. The construction of the index structure is independent of the similarity function, which can be specified at query time. The resulting similarity search algorithm shows excellent scalability with increasing memory availability and database size\n'